#+author: conao3
#+date: <2018-10-25 Thu>

[[https://github.com/conao3/develop][https://raw.githubusercontent.com/conao3/files/master/blob/headers/png/develop.png]]
[[https://github.com/conao3/develop/blob/master/LICENSE][https://img.shields.io/github/license/conao3/develop.svg?style=flat-square]]
[[https://github.com/conao3/develop/releases][https://img.shields.io/github/tag/conao3/develop.svg?style=flat-square]]
[[https://travis-ci.org/conao3/develop][https://img.shields.io/travis/conao3/develop/master.svg?style=flat-square]]
[[https://app.codacy.com/project/conao3/develop/dashboard][https://img.shields.io/codacy/grade/33d03999cdb9426abb716e23a8d11b1d.svg?logo=codacy&style=flat-square]]
[[https://www.patreon.com/conao3][https://img.shields.io/badge/patreon-@conao3-orange.svg?logo=patreon&style=flat-square]]
[[https://twitter.com/conao_3][https://img.shields.io/badge/twitter-@conao__3-blue.svg?logo=twitter&style=flat-square]]
[[https://join.slack.com/t/conao3-support/shared_invite/enQtNTg2MTY0MjkzOTU0LTFjOTdhOTFiNTM2NmY5YTE5MTNlYzNiOTE2MTZlZWZkNDEzZmRhN2E0NjkwMWViZTZiYjA4MDUxYTUzNDZiNjY][https://img.shields.io/badge/chat-on_slack-blue.svg?logo=slack&style=flat-square]]

* Table of Contents
- [[#description][Description]]
- [[#install][Install]]
- [[#usage][Usage]]
- [[#information][Information]]
  - [[#donation][Donation]]
  - [[#community][Community]]
  - [[#contribute][Contribute]]
  - [[#license][License]]
  - [[#author][Author]]
  - [[#contributors][Contributors]]

* Description
This is the ~dev~ folder located in conao3's ~$HOME~.
This folder contains the programming contest code and a small ~Makefile~
to manage the GitHub repository.

I created this repository mainly to manage that Makefile.

It could be help to manage your GitHub repository with some modifications.

* Install
Only clone it and ~make~ someting showed below.
#+begin_src sh
  cd
  git clone https://github.com/conao3/develop.git dev
#+end_src

~.make~, ~repos~ is managed Makefile
so should not add and remove folders.
~git~ is yours to manage other (someone or other hosted service) repositories.

Repositories placed under ~git~ will not be pushed by ~make push~,
but only fetch and merge updates of upstream with ~make pull~.

* Usage
** make
~make~ runs ~make $(DIRS)~ and ~make clone~ that prepare dirs and 
shallow clone all repositories hosted on GitHab.

** make clone 
~make clone~ shallow clone (fetch head tree only) all repositories
hosted on GitHub as conao3 to ~repos~.
#+begin_src bash
  $ make
    > mkdir -p .make
    > mkdir -p repos
    > git clone --depth 1 git@github.com:conao3/adder.y.git repos/adder.y
    > git clone --depth 1 git@github.com:conao3/apel.el.git repos/apel.el
    > git clone --depth 1 git@github.com:conao3/auto-save-buffers.el.git repos/auto-save-buffers.el
    > ...
#+end_src

** make unshallow
~make unshallow~ unshallow repositories (fetch whole repository)
for fetched by ~make clone~ for repositories in ~repos~.

** make pull
~make pull~ pull repositories from origin and from its current branch
for repositories in ~repos~ and ~git~.
 
** make push
~make push~ push repositories to origin and to current branch
for repositories in ~repos~.

** make clean
~make clean~ move ~$(DIRS)~; ~.make~, ~repos~ and ~git~ to ~trash-$(UUID)~ folder
(not remove them. just move).

* Information
** Donation
I love OSS and I am dreaming of working on it as *full-time* job.

*With your support*, I will be able to spend more time at OSS!

[[https://www.patreon.com/conao3][https://c5.patreon.com/external/logo/become_a_patron_button.png]]

** Community
All feedback and suggestions are welcome!

You can use github issues, but you can also use [[https://join.slack.com/t/conao3-support/shared_invite/enQtNTg2MTY0MjkzOTU0LTFjOTdhOTFiNTM2NmY5YTE5MTNlYzNiOTE2MTZlZWZkNDEzZmRhN2E0NjkwMWViZTZiYjA4MDUxYTUzNDZiNjY][Slack]]
if you want a more casual conversation.

** Contribution
Feel free to send PR!

** License
#+begin_example
  The MIT License (MIT)
  Copyright (c) Naoya Yamashita - https://conao3.com
  https://github.com/conao3/develop/blob/master/LICENSE
#+end_example

** Author
- Naoya Yamashita ([[https://github.com/conao3][conao3]])

** Contributors
- Not yet... Now send PR and add your name!!
